export const PAKISTAN_CITIES: string[] = [
  "Lahore",
  "Karachi",
  "Islamabad",
  "Rawalpindi",
  "Faisalabad",
  "Multan",
  "Peshawar",
  "Quetta",
  "Sialkot",
  "Gujranwala",
  "Hyderabad",
  "Abbottabad",
  "Ahmedpur East",
  "Ali Khan Abad",
  "Alipur",
  "Arifwala",
  "Attock",
  "Badin",
  "Bagh",
  "Bahawalnagar",
  "Bahawalpur",
  "Bannu",
  "Batkhela",
  "Bhai Pheru",
  "Bhakkar",
  "Bhalwal",
  "Bhimber",
  "Burewala",
  "Charsadda",
  "Chichawatni",
  "Chiniot",
  "Chishtian",
  "Chitral",
  "Chunian",
  "Dadu",
  "Daska",
  "Dera Ghazi Khan",
  "Dera Ismail Khan",
  "Dina",
  "Fateh Jang",
  "Gaarho",
  "Gadoon Amazai",
  "Ghotki",
  "Gilgit",
  "Gojra",
  "Gujar Khan",
  "Gujrat",
  "Hafizabad",
  "Hangu",
  "Haripur",
  "Hasilpur",
  "Haveli Lakha",
  "Hazro",
  "Hub",
  "Jacobabad",
  "Jaranwala",
  "Jauharabad",
  "Jhang",
  "Jhelum",
  "Kabirwala",
  "Kamalia",
  "Kamoke",
  "Kandhkot",
  "Karak",
  "Kasur",
  "Khairpur",
  "Khanewal",
  "Khanpur",
  "Kharian",
  "Khushab",
  "Kohat",
  "Kot Addu",
  "Kotli",
  "Kotri",
  "Lalamusa",
  "Larkana",
  "Layyah",
  "Liaquatpur",
  "Lodhran",
  "Loralai",
  "Mailsi",
  "Malakwal",
  "Mandi Bahauddin",
  "Mansehra",
  "Mardan",
  "Mian Channu",
  "Mianwali",
  "Mingora",
  "Mirpur (AJK)",
  "Mirpur Khas",
  "Muridke",
  "Murree",
  "Muzaffarabad",
  "Muzaffargarh",
  "Nankana Sahib",
  "Narowal",
  "Nawabshah",
  "Nowshera",
  "Okara",
  "Pakpattan",
  "Pasrur",
  "Pattoki",
  "Pind Dadan Khan",
  "Pindi Bhattian",
  "Pir Mahal",
  "Rahim Yar Khan",
  "Raiwind",
  "Rajanpur",
  "Rawalakot",
  "Renala Khurd",
  "Sadiqabad",
  "Sahiwal",
  "Sambrial",
  "Samundri",
  "Sargodha",
  "Sehwan Sharif",
  "Shahdadkot",
  "Shahdadpur",
  "Sheikhupura",
  "Shikarpur",
  "Shorkot",
  "Sukkur",
  "Swabi",
  "Swat",
  "Talagang",
  "Tandlianwala",
  "Tando Adam",
  "Tando Allahyar",
  "Tando Muhammad Khan",
  "Taunsa",
  "Taxila",
  "Toba Tek Singh",
  "Turbat",
  "Umerkot",
  "Vehari",
  "Wah Cantt",
  "Wazirabad",
  "Zhob",
  "Other",
];
